version: "2"
services:
  data:
    build: ./docker/data
    container_name: ${PREFIX_NAME}_data
    volumes:
      - ./data/html:/var/www/html
      - ./data/mysql:/var/lib/mysql

  web:
    build: ./docker/web
    container_name: ${PREFIX_NAME}_web
    volumes_from:
      - data
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    links:
      - db
      - cache
#      - elasticsearch

  composer:
    build: ./docker/composer
    container_name: ${PREFIX_NAME}_composer
    volumes_from:
      - data
    links:
      - db
      - cache
    working_dir: /var/www/html

  db:
    build:
      # You can switch as needed
      # context: ./docker/db/mariadb
      context: ./docker/db/mysql
    container_name: ${PREFIX_NAME}_db
    volumes_from:
      - data
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      # MYSQL_ROOT_PASSWORD: root
      # If you want to set mysql user manually, remove these comments:
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
      # MYSQL_DATABASE: app
      # MYSQL_HOST: ""
      TZ: "Asia/Tokyo"
    env_file: .env
    mem_limit: 1000000000

  cache:
    build: ./docker/cache/redis
    #build: ./docker/cache/memcached
    container_name: ${PREFIX_NAME}_cache

  yarn:
    build: ./docker/yarn
    container_name: ${PREFIX_NAME}_yarn
    volumes_from:
      - data

#  elasticsearch:
#    image: "elasticsearch:2.4"
#    container_name: elasticsearch
