version: "2"
services:
  data:
    build: ./docker/data
    container_name: ${PREFIX_NAME}_data
    volumes:
      - ./data/html:/var/www/html
      - ./data/mysql:/var/lib/mysql

  web:
    build: ./docker/web
    env_file: .env
    environment:
      PHP_SOCKET: php:9000
    container_name: ${PREFIX_NAME}_web
    volumes_from:
      - data
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    links:
      - php

  php:
    build: ./docker/php
    container_name: ${PREFIX_NAME}_php
    volumes_from:
      - data
    expose:
      - 9000
    links:
      - db
      - cache

  composer:
    build: ./docker/composer
    container_name: ${PREFIX_NAME}_composer
    volumes_from:
      - data
    links:
      - db
      - cache
    working_dir: /var/www/html

  db:
    build:
      # You can switch as needed
      # context: ./docker/db/mariadb
      context: ./docker/db/mysql
    container_name: ${PREFIX_NAME}_db
    volumes_from:
      - data
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      TZ: "Asia/Tokyo"
    env_file: .env
    mem_limit: 1000000000

  cache:
    build: ./docker/cache/redis
    #build: ./docker/cache/memcached
    container_name: ${PREFIX_NAME}_cache

  yarn:
    build: ./docker/yarn
    container_name: ${PREFIX_NAME}_yarn
    volumes_from:
      - data
